name: CI

on: [push]

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: [ubuntu-18.04]
    steps:
      - uses: actions/checkout@v1
      - name: Push to IPFS
        uses: aquiladev/ipfs-action@v0.1.5
        with:
          path: ./docs
          pinataKey: ${{ secrets.PINATA_KEY }}
          pinataSecret: ${{ secrets.PINATA_SECRET }}
          pinataPinName: ${{ secrets.PINATA_PIN_NAME }}
